### PR TITLE
Move iron-form to our fork that implements <slot> fix

### PR DESCRIPTION
**Pull request by MatthijsKok**
obviously needs testing to see if this fixes our issue.

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
This doesn't change anything since the `2.0.0` tag is also set on the base repo

**Comment by FrancisBehnen** [comment]
Ehm sorry, judged too soon, but what I think you meant to do was pick the `2.0-preview` 'release', since that's the branch being merged in https://github.com/PolymerElements/iron-form/pull/158

**Comment by FrancisBehnen** [comment]
Unfortunately switching to `firmfirm:2.0-preview` doesn't help either :(

**Comment by skamoen** [comment]
Tested this with enctype fix which seems to work. @FrancisBehnen Can you verify?

**Comment by FrancisBehnen** [comment]
Payload is correct 🎉 
Status code is also `200` but I'm not getting logged in

**Review by FrancisBehnen — COMMENTED** [review]
Payload is correct 🎉
Status code is also 200 but I'm not getting logged in..

I also feel like we should just depend on the repo we forked from, since we didn't change anything.

**Comment by skamoen** [comment]
If we depend on a remote repo that's meant to be merged, we lose control over it.

 I'll dig a bit further to see why we're not logged in

**Comment by skamoen** [comment]
Event handlers were in the wrong tag. Last commit fixes it.

**Pull request merged**
